//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bp_bms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id { get; set; }
        public string itemID { get; set; }
        public string accID { get; set; }
        public int vid { get; set; }
        public string vname { get; set; }
        public string name { get; set; }
        public int measurementID { get; set; }
        public string purchaseDiscription { get; set; }
        public string saleDiscription { get; set; }
        public decimal cost { get; set; }
        public decimal price { get; set; }
    }
}
