//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bp_bms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class measurement
    {
        public int id { get; set; }
        public int measurementID { get; set; }
        public string code { get; set; }
        public string discription { get; set; }
        public decimal total { get; set; }
        public System.DateTime date { get; set; }
    }
}
