//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bp_bms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public string accID { get; set; }
        public int invoiceID { get; set; }
        public string vendorInvoiceNo { get; set; }
        public string vid { get; set; }
        public string vname { get; set; }
        public decimal invAmount { get; set; }
        public decimal amtPaid { get; set; }
        public decimal balance { get; set; }
        public decimal amtToPay { get; set; }
        public System.DateTime date { get; set; }
    }
}
