//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bp_bms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class puchaseOrder
    {
        public int id { get; set; }
        public string itemID { get; set; }
        public int measurementID { get; set; }
        public string vid { get; set; }
        public byte[] vname { get; set; }
        public decimal qty { get; set; }
        public decimal discount { get; set; }
        public decimal amount { get; set; }
    }
}
