//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bp_bms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bmsEntitiesPurchasing : DbContext
    {
        public bmsEntitiesPurchasing()
            : base("name=bmsEntitiesPurchasing")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<accountHead> accountHeads { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<measurement> measurements { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<puchaseOrder> puchaseOrders { get; set; }
        public virtual DbSet<purchaseinvoice> purchaseinvoices { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
    }
}
