//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bp_bms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vendor
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Vendor Identification")]
        [Required]
        public string vid { get; set; }
        [Display(Name = "Account ID")]
        [Required]
        public string accID { get; set; }
        [Display(Name = "First Name")]
        [Required]
        public string fname { get; set; }
        [Display(Name = "Last Name")]
        [Required]
        public string lname { get; set; }
        [Display(Name = "Postal Address")]
        [Required]
        public string address { get; set; }
        [Display(Name = "Contact Number")]
        [Required]
        public string phone { get; set; }
        [Display(Name = "Email Address")]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Select Bank Account")]
        public string BankName { get; set; }
        [Display(Name = "Bank Account Title of Vendor")]
        public string BankAcTitle { get; set; }
        [Display(Name = "Bank Account Number")]
        public string BankAcNo { get; set; }
    }
}
